In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# lets data with 2 feature numpy array
data = np.array([[3,2],[3,3],[6,5],[6,7]])

df = pd.DataFrame(data, columns=['Feature_1', 'Feature_2'])

df.head()

   Feature_1  Feature_2
0          3          2
1          3          3
2          6          5
3          6          7

In [3]:
# compute the distance
new_point = np.array([3,2])
df['Distance'] = np.sqrt((df['Feature_1'] - new_point[0])**2 + (df['Feature_2'] - new_point[1])**2)
df.head()

   Feature_1  Feature_2  Distance
0          3          2  0.000000
1          3          3  1.000000
2          6          5  4.242641
3          6          7  5.830952

In [6]:
# lets compute cosine similarity
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(data, new_point.reshape(1, -1))
df['Cosine_Similarity'] = similarity
df.head()

   Feature_1  Feature_2  Distance  Cosine_Similarity
0          3          2  2.000000           0.942990
1          3          3  1.000000           0.989949
2          6          5  3.162278           0.973080
3          6          7  4.242641           0.997880

In [5]:
# lets say there 3 products with their prices  ratings and names
products = np.array([[100, 4.5, 'Product 1'],[150, 4.0, 'Product 2'],[200, 5.0, 'Product 3'],[120, 3.5, 'Product 4']])
products_df = pd.DataFrame(products, columns=['Price', 'Rating', 'Name'])


# new product
new_product = np.array([121, 4.2])

# letc compute euclidean distance
products_df['Distance'] = np.sqrt((products_df['Price'].astype(float) - new_product[0])**2 + (products_df['Rating'].astype(float) - new_product[1])**2)
products_df.head()

  Price Rating       Name   Distance
0   100    4.5  Product 1  21.002143
1   150    4.0  Product 2  29.000690
2   200    5.0  Product 3  79.004051
3   120    3.5  Product 4   1.220656